"""Konstanta string untuk event audit khusus web dashboard."""


class AuditEvents:
    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED"
    ADMIN_LOGOUT = "ADMIN_LOGOUT"
    TICKET_STATUS_UPDATED = "TICKET_STATUS_UPDATED"
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_ESCALATION_UPDATED = "TICKET_ESCALATION_UPDATED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    FILE_DOWNLOADED = "FILE_DOWNLOADED"


TICKET_STATUSES = ("PENDING_REVIEW", "IN_PROGRESS", "RESOLVED", "CLOSED", "REJECTED")
ESCALATION_LEVELS = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
